version: 2

models:
  - name: re_data_last_metrics
    description: >
      Last metric value for all gathered metrics. This tables aggregates those
      last metrics from all metrics tables.
      Metrics from this table are later used for anomalies detection.

  - name: re_data_last_stats
    description: >
      Stats avg, stddev for all gathered metrics in last period (Starting from anamaly_detection_time_window_start variable)
      This tables aggregates those last metrics from all metrics tables.
      Stats from this table are later used for anomalies detection.


  