# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 're_data'
version: '0.1.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 're_data_postgres'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs_blocks"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"
vars:
    re_data:time_window_end: '2021-06-03 00:00:00' #overwitten when running by re_data
    re_data:time_window_start: '2021-06-02 00:00:00' #overwitten when running by re_data
    re_data:anomaly_detection_window_start: '2021-05-02 00:00:00' #overwitten when running by re_data
    re_data:actively_monitored_by_default: false

    re_data:alerting_z_score: 3
    re_data:schemas:
        - your_schema_name #overwitten when running by re_data

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

require-dbt-version: [">=0.19.1", "<0.20.0"]

models:
  re_data:
    +schema: re
