version: 2

models:
  - name: re_min_length
    columns:
      - name: value
        tests:
          - values_between:
              table_name: 'javascript.pages'
              low: 10
              high: 100