name: 'dbt_re_data_integration_tests'
version: '1.0'
config-version: 2

# Changed when running tests
profile: 're_data_postgres'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

seeds:
  +schema: raw
  +quote_columns: false

  dbt_re_data_integration_tests:
    expected:
      +schema: expected
      
      expected_sample_data_row_count:
        +column_types:
          time_window_start: 'TIMESTAMP'
          time_window_end: 'TIMESTAMP'
          computed_on: 'TIMESTAMP'

      expected_sample_data_freshness:
        +column_types:
          time_window_end: 'TIMESTAMP'
          computed_on: 'TIMESTAMP'
    
      expected_sample_data_max:
        +column_types:
          time_window_start: 'TIMESTAMP'
          time_window_end: 'TIMESTAMP'

      expected_sample_data_max_length:
        +column_types:
          time_window_start: 'TIMESTAMP'
          time_window_end: 'TIMESTAMP'