name: 're_data_integration_tests'
version: '1.0'
config-version: 2

# Changed when running tests
profile: 're_data_postgres'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

vars:
    
  re_data:tables:
    - name: sample_table
      actively_monitored: true
      time_filter: creation_time

    - name: sample_with_anomaly
      actively_monitored: true
      time_filter: creation_time

  re_data:metrics_base:
    table:
      - row_count
      - freshness
      - buy_count
      
    column:
      numeric:
        - min
        - max
        - avg
        - stddev
        - variance
        - count_nulls
        - diff
        
      text:
        - min_length
        - max_length
        - avg_length
        - count_nulls
        - count_missing

seeds:
  +schema: raw
  +quote_columns: false

  re_data_integration_tests:
    expected:
      +schema: expected
      
      expected_sample_data_row_count:
        +column_types:
          time_window_start: 'TIMESTAMP'
          time_window_end: 'TIMESTAMP'

      expected_sample_data_freshness:
        +column_types:
          time_window_end: 'TIMESTAMP'
    
      expected_sample_data_max:
        +column_types:
          time_window_start: 'TIMESTAMP'
          time_window_end: 'TIMESTAMP'

      expected_sample_data_max_length:
        +column_types:
          time_window_start: 'TIMESTAMP'
          time_window_end: 'TIMESTAMP'

      expected_sample_data_z_score:
        +column_types:
          time_window_end: 'TIMESTAMP'