version: 2

models:

  - name: re_data_freshness_inc
    description: >
     Internal table representing freshness (number of seconds since last insert) for all monitored tables
    
    columns:
      - name: table_name
        tests:
          - not_null
          - relationships:
              to: ref('re_data_tables')
              field: table_name

      - name: column_name
        description:
          Field is present here for compatiblity reasons, it should be always equal to empty string
        tests:
          - not_null
          - accepted_values:
              values: ['']

      - name: metric
        tests:
          - not_null

      - name: value
        description: >
          Value of freshness, it *can* be null in case of no new records existing in given time frame.

      - name: time_window_end
        tests:
          - not_null
      
      - name: computed_on
        tests:
          - not_null
