
version: 2

models:
    - name: re_monitored_tables
      description: "Model representing tables ;) to be monitored for anomalies"
      columns:
        - name: table_name
          description: "Full name schema + table name of a monitored table"
          tests:
            - unique
            - not_null

    - name: re_monitored_columns
      description: "Model representing all columns of tables"

